---

- name: "Copy over the keystore"
  copy:
    src: "{{ keystore_path }}"
    dest: /home/ubuntu/cert/{{ keystore_path | basename }}
    mode: '0600'
    owner: "ubuntu"
    group: "ubuntu"

#- name: restart sshd
#  command: service ssh restart

#- name: Reboot for security updates
#  reboot:
#    reboot_timeout: 3600
