---
- hosts: all
  become: true
  roles:
    - citizen-pack
    - ansible-hardening
    - ansible-os-hardening
    - ansible-ssh-hardening
    - role-secure-docker-daemon
    - node-clean-up
    - disable-ipv6
    - install-packages
    - mount-volumes
    - setup-app-block42
    - keystore
