version: '3'
services:
  nginx:
{% if nginx_make=="block42" %}
    depends_on:
      - prep
    restart: always
    image: 'nginx:1.17.3'
    container_name: 'nginx'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/access_lists/:/etc/nginx/access_lists/
      - ./nginx/log/:/var/log/nginx/
    ports:
      - '9000:9000'
      - '7100:7100'
    external_links:
      - prep
{% endif %}
{% if nginx_make=="prep_docker" %}
    image: 'looploy/nginx:1.17.1'
    container_name: nginx_1.17
    environment:
      NGINX_LOG_OUTPUT: 'file'
      NGINX_LOG_TYPE: 'main'
      NGINX_USER: 'root'
      VIEW_CONFIG: "yes"
      USE_NGINX_THROTTLE: "yes"
      NGINX_THROTTLE_BY_URI: "yes"
      NGINX_RATE_LIMIT: "200r/s"
      NGINX_BURST: "5"
      NGINX_SET_NODELAY: "no"
      GRPC_PROXY_MODE: "yes"
      USE_VTS_STATUS: "yes"
      TZ: "GMT-9"
      SET_REAL_IP_FROM: "0.0.0.0/0"
      PREP_MODE: "yes"
      NODE_CONTAINER_NAME: "prep"
      PREP_NGINX_ALLOWIP: "yes"
      NGINX_ALLOW_IP: "0.0.0.0/0"
      NGINX_LOG_FORMAT: '$$realip_remote_addr $$remote_addr  $$remote_user [$$time_local] $$request $$status $$body_bytes_sent $$http_referer "$$http_user_agent" $$http_x_forwarded_for $$request_body'
    volumes:
       - ./data/loopchain/nginx:/var/log/nginx
       - ./user_conf:/etc/nginx/user_conf
    ports:
       - '7100:7100'
       - '9000:9000'
{% endif %}

  prep:
    image: 'iconloop/prep-node:1910261021xc97f33'
    container_name: "prep"
    environment:
      NETWORK_ENV: "mainnet"
      LOG_OUTPUT_TYPE: "file"
      SWITCH_BH_VERSION3: "10324749"
      CERT_PATH: "/cert"
      LOOPCHAIN_LOG_LEVEL: "SPAM"
      ICON_LOG_LEVEL: "DEBUG"
      FASTEST_START: "yes"
      DEFAULT_PATH: "/data/loopchain"
      iissCalculatePeriod: "1800"
      termPeriod: "1800"
      ENDPOINT_URL: "https://zicon.net.solidwallet.io"
{% if keystore_path is defined %}
      PRIVATE_PATH: "/cert/{{ keystore_path | basename }}"
      PRIVATE_PASSWORD: "{{ keystore_password | default()}}" # Manually ssh into box to deploy
{% endif %}
    restart: always
    cap_add:
      - SYS_TIME
    volumes:
      - ./data:/data
      - ./cert:/cert
{% if nginx_make=="prep_docker" %}
    ports:
      - '9000'
      - '7100'
{% endif %}
{% if log_server_ip is defined %}
  loop-logger:
    image: looploy/fluentd
    container_name: loop_logger
    restart: always
    network_mode: host
    volumes:
      - ./data/:/loopchain/log
      - ./fluent/log:/fluentd/log
    environment:
      LOG_SERVER_IP: "{{ log_server_ip }}"
{% endif %}