---

- name: "Add docker apt key"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

# Release part can probably be templated using ansible facts.
- name: "Install docker apt repository for bionic"
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: "Update repositories cache"
  apt:
    update_cache: yes

- name: "Upgrade packages to the latest version"
  apt:
    upgrade: dist

- name: "Install required packages"
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - build-essential
      - python
      - python3
      - python-apt
      - python3-apt
      - python-pip
      - python3-pip
      - linux-aws
      - awscli
      - docker-ce
      - jq

- name: "Add user to docker group"
  user:
    name: ubuntu
    groups: docker
    append: yes

- name: "Enable docker service, and start it"
  systemd:
    name: docker
    enabled: yes
    masked: no
    state: started

- name: "Install docker packages"
  pip:
    name: "{{ pippkgs }}"
    state: latest
  vars:
    pippkgs:
      - docker
      - docker-compose
      - PyYAML 

- name: "Create hard core limit file"
  file:
    path: /etc/security/limits.d/10.hardcore.conf
    mode: '0644'
    state: touch
    owner: root
    group: root
